### ISSUE TITLE
Feature: Make initStandaloneModeLogger public

### ISSUE THREAD

**Issue by alarbada** [ConduitIO/conduit-connector-sdk#105]
### Feature description

I first thought that it would be useful to allow the acceptance tests to have a custom context. But after digging further on why didn't a `sdk.Logger(ctx).Info()` call log anything, I found out that the used zerolog instance is the disabled one.

Specifically, this:

```go

func initStandaloneModeLogger() error {
	// adjust field names to have parity with hclog, go-plugin uses hclog to
	// parse log messages
	zerolog.LevelFieldName = "@level"
	zerolog.CallerFieldName = "@caller"
	zerolog.TimestampFieldName = "@timestamp"
	zerolog.MessageFieldName = "@message"

	logger := zerolog.New(os.Stderr)

	// here the default context logger is set, but initStandaloneModeLogger is only called on sdk.serve, not when I'm developing connectors
	zerolog.DefaultContextLogger = &logger 
	return nil
}
```

It might be confusing for future connector developers to not see any logs when calling `sdk.Logger(ctx).Info()`, as it was confusing for me.

Solutions to this problem that I can think of:

1. make initStandaloneModeLogger public, and allow sdk consumers to initialize the logger
2. add an init call in `logger.go` that sets up `zerolog.DefaultContextLogger`
3. add an additional `InitLogger` function that does the same as initStandaloneModeLogger, but meant for testing purposes.

I have to add also that this is not that important for me anymore, as I know now why I did not see logs on my tests. I can just set the DefaultContextLogger myself on my test code.

**Comment by simonl2002** [comment]
We won't implement this specific change but we will update the documentation.
