### ISSUE TITLE
Update all connectors to latest sdk

### ISSUE THREAD

**Issue by raulb** [ConduitIO/conduit-connector-sdk#173]
⚠️ We need to make sure those connectors are also released once upgraded.

> [!IMPORTANT]
> After updating the SDK run this script to fix 95% of the code automatically: https://github.com/ConduitIO/conduit/issues/1433#issuecomment-2181110340

- [x] https://github.com/ConduitIO/conduit-connector-file @ v0.10.0
- [x] https://github.com/ConduitIO/conduit-connector-generator @ v0.10.0
- [x] https://github.com/ConduitIO/conduit-connector-kafka @ v0.10.0
- [x] https://github.com/ConduitIO/conduit-connector-log @ v0.10.0
- [x] https://github.com/ConduitIO/conduit-connector-postgres @ v0.10.0
- [x] https://github.com/ConduitIO/conduit-connector-s3 @ v0.10.0
- [x] https://github.com/conduitio-labs/conduit-connector-activemq-artemis @ v0.10.0
- [x] https://github.com/conduitio-labs/conduit-connector-activemq-classic @ v0.10.0
- [x] https://github.com/conduitio-labs/conduit-connector-azure-storage @ v0.10.0
- [x] https://github.com/conduitio-labs/conduit-connector-clickhouse @ v0.10.0
- [x] https://github.com/conduitio-labs/conduit-connector-dynamodb @ v0.10.0
- [x] https://github.com/conduitio-labs/conduit-connector-http @ v0.10.0
- [x] https://github.com/conduitio-labs/conduit-connector-kinesis @ v0.10.0
- [x] https://github.com/conduitio-labs/conduit-connector-mongo @ v0.10.0
- [x] https://github.com/conduitio-labs/conduit-connector-mysql @ v0.10.0
- [x] https://github.com/conduitio-labs/conduit-connector-pinecone @ v0.10.0
- [x] https://github.com/conduitio-labs/conduit-connector-pulsar @ v0.10.0
- [x] https://github.com/conduitio-labs/conduit-connector-rabbitmq @ v0.10.0
- [x] https://github.com/conduitio-labs/conduit-connector-salesforce @ v0.10.0
- [x] https://github.com/conduitio-labs/conduit-connector-sqs @ v0.10.0
- [ ] https://github.com/conduitio-labs/conduit-connector-airtable/issues/10
- [ ] https://github.com/conduitio-labs/conduit-connector-algolia/issues/7
- [ ] https://github.com/conduitio-labs/conduit-connector-azure-event-hub/issues/22
- [ ] https://github.com/conduitio-labs/conduit-connector-benthos/issues/7
- [ ] https://github.com/conduitio-labs/conduit-connector-bigquery/pull/50
- [x] https://github.com/conduitio-labs/conduit-connector-cassandra @ v0.9.1
- [x] https://github.com/conduitio-labs/conduit-connector-chaos @ v0.7.2
- [ ] https://github.com/conduitio-labs/conduit-connector-cosmos-nosql/pull/55
- [ ] https://github.com/conduitio-labs/conduit-connector-databricks/pull/70
- [ ] https://github.com/conduitio-labs/conduit-connector-db2/pull/119
- [ ] https://github.com/conduitio-labs/conduit-connector-elasticsearch/pull/94
- [ ] https://github.com/conduitio-labs/conduit-connector-firebolt/pull/103
- [ ] https://github.com/conduitio-labs/conduit-connector-gcp-pubsub/pull/262
- [ ] https://github.com/conduitio-labs/conduit-connector-google-cloudstorage/pull/42
- [ ] https://github.com/conduitio-labs/conduit-connector-google-sheets/pull/196
- [ ] https://github.com/conduitio-labs/conduit-connector-grpc-client/issues/98
- [ ] https://github.com/conduitio-labs/conduit-connector-grpc-server/issues/46
- [ ] https://github.com/conduitio-labs/conduit-connector-hubspot/pull/103
- [ ] https://github.com/conduitio-labs/conduit-connector-marketo/issues/39
- [ ] https://github.com/conduitio-labs/conduit-connector-materialize/pull/101
- [x] https://github.com/conduitio-labs/conduit-connector-nats-jetstream @ v0.9.1 @hariso 
- [x] https://github.com/conduitio-labs/conduit-connector-nats-pubsub @ v0.9.1 @lovromazgon 
- [ ] https://github.com/conduitio-labs/conduit-connector-neo4j/pull/89
- [ ] https://github.com/conduitio-labs/conduit-connector-notion/pull/79
- [ ] https://github.com/conduitio-labs/conduit-connector-oracle/pull/155 
- [ ] https://github.com/conduitio-labs/conduit-connector-redis/pull/116
- [ ] https://github.com/conduitio-labs/conduit-connector-redpanda/pull/19
- [ ] https://github.com/conduitio-labs/conduit-connector-redshift/pull/98
- [ ] https://github.com/conduitio-labs/conduit-connector-sap-hana/pull/207
- [x] https://github.com/conduitio-labs/conduit-connector-snowflake @ v0.9.1
- [ ] https://github.com/conduitio-labs/conduit-connector-sql-server/pull/104
- [ ] https://github.com/conduitio-labs/conduit-connector-stripe/pull/32
- [ ] https://github.com/conduitio-labs/conduit-connector-vitess/issues/139
- [ ] https://github.com/conduitio-labs/conduit-connector-weather/pull/43
- [x] https://github.com/conduitio-labs/conduit-connector-weaviate @ v0.7.2
- [ ] https://github.com/conduitio-labs/conduit-connector-zendesk/pull/63
- [ ] https://github.com/conduitio-labs/conduit-connector-zeromq/pull/13

**Comment by hariso** [comment]
For NATS JetStream, the work is done here: https://github.com/conduitio-labs/conduit-connector-nats-jetstream/pull/137.

**Comment by raulb** [comment]
Generated by using this script

```bash
#!/bin/bash

# Check that a tag was provided as an argument
if [ -z "$1" ]; then
  echo "Usage: $0 <tag>"
  exit 1
fi

connectors=$(curl -s https://conduit.io/connectors.json | jq -c '.[].url')
connectors_without_commit=()
connectors_without_sdk=()

for url in $(echo "$connectors"); do
  github_url=${url#*github.com/}
  github_url=${github_url%%\"*}
  raw_url="https://raw.githubusercontent.com/$github_url/main/go.mod"

  if ! curl -sL "$raw_url" >/dev/null 2>&1; then
    connectors_without_sdk+=("https://github.com/$github_url")
    continue
  fi

  go_mod=$(curl -s "$raw_url")

  commit=$(awk -F' ' '/github.com\/conduitio\/conduit-connector-sdk/{print $NF}' <<< "$go_mod")

  if [ "$commit" = "github.com/conduitio/conduit-connector-sdk" ]; then
    commit=$(awk -F' ' '/require github.com\/conduitio\/conduit-connector-sdk/{print $3}' <<< "$go_mod")
  fi

  if ! grep -q "github.com/conduitio/conduit-connector-sdk $1" <<< "$go_mod"; then
    if [ -z "$commit" ]; then
      connectors_without_sdk+=("https://github.com/$github_url")
    else
      connectors_without_commit+=("https://github.com/$github_url @ $commit")
    fi
  else
    echo "- [x] https://github.com/$github_url @ $commit"
  fi
done

if [ "${#connectors_without_commit[@]}" -gt 0 ]; then
  for connector in "${connectors_without_commit[@]}"; do
    echo "- [ ] $connector"
  done
fi

if [ "${#connectors_without_sdk[@]}" -gt 0 ]; then
  echo "
### Connectors without conduit-connector-sdk:
"
  for connector in "${connectors_without_sdk[@]}"; do
    echo "- [ ] $connector"
  done
fi
exit 0
```

**Comment by alarbada** [comment]
@raulb do you mind if I help you out with some of my connectors?

Specifically with these:

- pinecone
- activemq artemis & classic
- pulsar
- rabbitmq

Also, I took a look at some of these:

- Pinecone needs the {{ secrets.API_KEY }} set, for some reason it is not there anymore.
- activemq artemis has many dependabot prs blocked, might be misconfigured.
- activemq classic got a failed to create review: GraphQL: GitHub Actions is not permitted to approve pull requests. (addPullRequestReview), might also be misconfigured.

**Comment by raulb** [comment]
@alarbada please do so!!! thank you!

**Comment by raulb** [comment]
Closing this one since we'll address the upgrade to the latest SDK for each connector independently.
