### ISSUE TITLE
paramgen: ignore todo comments above fields

### ISSUE THREAD

**Issue by hariso** [ConduitIO/conduit-connector-sdk#68]
### Feature description

The following code (notice the todo):
```go
type Config struct {
	// Personal access token.
	// More description.
	// todo test
	Token string `json:"token" validate:"required"`
}
```

generates: 

`Description: "Personal access token. More description. todo test"`

Ideally, `// todo test` is ignored.

**Comment by simonl2002** [comment]
if there's no movement here in 3mnths close this one out.

**Comment by hariso** [comment]
Closing as per @simonl2002's comment above.
